# Generated by Django 4.1.7 on 2023-02-24 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('date_of_release', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_time', models.IntegerField()),
                ('available_seat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=5)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.screen')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('seat_booked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.seat')),
            ],
        ),
        migrations.CreateModel(
            name='TheaterList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theatername', models.CharField(max_length=200)),
                ('NoOfScreen', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('about', models.CharField(max_length=500)),
                ('movielist', models.ManyToManyField(to='main.movies')),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Screen_no', models.CharField(max_length=200)),
                ('show_times', models.CharField(choices=[('mrng', '10:30'), ('aftrn', '1:30'), ('mrng', '6:30'), ('night', '9:30')], max_length=100)),
                ('total_seat', models.IntegerField()),
                ('running_movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movies')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.theaterlist')),
            ],
        ),
        migrations.AddField(
            model_name='screen',
            name='Screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.theater'),
        ),
        migrations.AddField(
            model_name='screen',
            name='booked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
        migrations.AddField(
            model_name='screen',
            name='show_movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movies'),
        ),
    ]
