# Generated by Django 4.1.7 on 2023-02-24 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_theaterlist_noofscreen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='booked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
    ]
