# Generated by Django 4.1.7 on 2023-02-24 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_screen_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='Screen_no',
        ),
        migrations.RemoveField(
            model_name='theater',
            name='running_movies',
        ),
        migrations.RemoveField(
            model_name='theater',
            name='show_times',
        ),
        migrations.RemoveField(
            model_name='theater',
            name='theater',
        ),
        migrations.RemoveField(
            model_name='theater',
            name='total_seat',
        ),
        migrations.AddField(
            model_name='screen',
            name='Theater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.theater'),
        ),
        migrations.AddField(
            model_name='theater',
            name='NoOfScreen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='theater_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='date_of_release',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='screen',
            name='available_seat',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='screen',
            name='show_movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.movies'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='show_time',
            field=models.TimeField(),
        ),
        migrations.DeleteModel(
            name='TheaterList',
        ),
    ]
