# Generated by Django 4.1.7 on 2023-02-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_theater_screen_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen',
            name='booked',
        ),
    ]
