# Generated by Django 4.1.7 on 2023-02-25 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_screen_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='Theater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.theater'),
        ),
    ]
