# Generated by Django 4.1.7 on 2023-02-25 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='Movies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.movies'),
        ),
    ]
